public enum InputLobbyHeaders
{
    CREATE_NEW_LOBBY_SESSION_RESULT = 0,
    UPDATE_LOBBY_SESSION_LIST_INFO = 1,
    LOBBY_SESSION_JOIN_INFO = 2,
    ENTER_LOBBY_SESSION_RESULT = 3,
    CLOSE_LOBBY_SESSION_INFO = 4,
    SEND_MESSAGE_TO_LOBBY_SESSION_CHAT_RESULT = 5,
    NEW_LOBBY_SESSION_CHAT_MESSAGE_INFO = 6,
    VALIDATE_LOBBY_SESSION_RESULT = 7,
    EXIT_LOBBY_SESSION_INFO = 8,
    EXIT_LOBBY_SESSION_RESULT = 9,
    TOSS_A_COIN_INFO = 10,
    SET_PLAYER_CASTLE_INFO = 11,
    SET_PLAYER_ORDINAL_INFO = 12,
    SET_PARTICIPANT_FEE_INFO = 13,
    SET_PLAYER_HERO_INFO = 14
}