public enum OutputLobbyHeaders
{
    CREATE_NEW_LOBBY_SESSION_REQUEST = 0,
    ENTER_LOBBY_SESSION_REQUEST = 1,
    GET_LOBBY_SESSION_LIST_REQUEST = 2,
    SEND_MESSAGE_TO_LOBBY_SESSION_CHAT_REQUEST = 3,
    TOSS_A_COIN_REQUEST = 4,
    SET_PLAYER_ORDINAL_REQUEST = 5,
    SET_PLAYER_CASTLE_REQUEST = 6,
    START_GAME_REQUEST = 7,
    EXIT_LOBBY_SESSION_REQUEST = 8,
    SET_PARTICIPANT_FEE_REQUEST = 9,
    SET_PLAYER_HERO_REQUEST = 10
}
