public enum OutputGameHeaders
{
    GIVE_UP_REQUEST = 0,
    LEAVE_GAME_REQUEST = 1,
    START_TURN_REQUEST = 2,
    END_TURN_REQUEST = 3,
    MOVE_HERO_REQUEST = 4,
    BATTLE_ACTION_REQUEST = 5,
    GET_CASTLE_INFO_REQUEST = 6,
    ADD_CASTLE_BUILDING_REQUEST = 7,
    HIRE_CASTLE_CREATURE_REQUEST = 8,
    SUBMIT_HERO_STATE_REQUEST = 9,
    MOVE_HERO_TO_CASTLE_REQUEST = 10,
    MOVE_HERO_TO_GARRISON_REQUEST = 11,
    RELEASE_CREATURE_STACK_REQUEST = 12,
    UPGRADE_CREATURE_STACK_REQUEST = 13,
    LEAVE_CASTLE_REQUEST = 14,
    SUBMIT_TRADE_REQUEST = 15,
    GET_CASTLE_FULL_INFO_REQUEST = 16
}
